// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5OohfxW79x-maDCp_DnQMb5ytcXD7UPI',
    appId: '1:1002992843855:web:f836b23bcc90c4a43d3e3a',
    messagingSenderId: '1002992843855',
    projectId: 'edafit-f3738',
    authDomain: 'edafit-f3738.firebaseapp.com',
    storageBucket: 'edafit-f3738.firebasestorage.app',
    measurementId: 'G-W5B88QNZZY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBs7LZBr2P0_5m_JUThhx54yAdRZuyYeZ8',
    appId: '1:1002992843855:android:f04092ef10d7506c3d3e3a',
    messagingSenderId: '1002992843855',
    projectId: 'edafit-f3738',
    storageBucket: 'edafit-f3738.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgOARIrdyzRP0vA7mnYYblc7DWWiincSk',
    appId: '1:1002992843855:ios:326a0c78fa2456953d3e3a',
    messagingSenderId: '1002992843855',
    projectId: 'edafit-f3738',
    storageBucket: 'edafit-f3738.firebasestorage.app',
    iosBundleId: 'com.example.edafitapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgOARIrdyzRP0vA7mnYYblc7DWWiincSk',
    appId: '1:1002992843855:ios:326a0c78fa2456953d3e3a',
    messagingSenderId: '1002992843855',
    projectId: 'edafit-f3738',
    storageBucket: 'edafit-f3738.firebasestorage.app',
    iosBundleId: 'com.example.edafitapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5OohfxW79x-maDCp_DnQMb5ytcXD7UPI',
    appId: '1:1002992843855:web:a092124d4335eab03d3e3a',
    messagingSenderId: '1002992843855',
    projectId: 'edafit-f3738',
    authDomain: 'edafit-f3738.firebaseapp.com',
    storageBucket: 'edafit-f3738.firebasestorage.app',
    measurementId: 'G-950H3DLVHN',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyC5OohfxW79x-maDCp_DnQMb5ytcXD7UPI',
    appId: '1:1002992843855:web:f836b23bcc90c4a43d3e3a',
    messagingSenderId: '1002992843855',
    projectId: 'edafit-f3738',
    authDomain: 'edafit-f3738.firebaseapp.com',
    storageBucket: 'edafit-f3738.firebasestorage.app',
  );
}